// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p2p.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "p2p.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace p2p {

void protobuf_ShutdownFile_p2p_2eproto() {
  delete JingleMessage::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_p2p_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_p2p_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ::core::protobuf_AddDesc_core_2eproto();
  JingleMessage::default_instance_ = new JingleMessage();
  JingleMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_p2p_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_p2p_2eproto_once_);
void protobuf_AddDesc_p2p_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_p2p_2eproto_once_,
                 &protobuf_AddDesc_p2p_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_p2p_2eproto {
  StaticDescriptorInitializer_p2p_2eproto() {
    protobuf_AddDesc_p2p_2eproto();
  }
} static_descriptor_initializer_p2p_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int JingleMessage::kFromJidFieldNumber;
const int JingleMessage::kToJidFieldNumber;
const int JingleMessage::kContentFieldNumber;
#endif  // !_MSC_VER

JingleMessage::JingleMessage()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:p2p.JingleMessage)
}

void JingleMessage::InitAsDefaultInstance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  fromjid_ = const_cast< ::core::Jid*>(
      ::core::Jid::internal_default_instance());
#else
  fromjid_ = const_cast< ::core::Jid*>(&::core::Jid::default_instance());
#endif
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  tojid_ = const_cast< ::core::Jid*>(
      ::core::Jid::internal_default_instance());
#else
  tojid_ = const_cast< ::core::Jid*>(&::core::Jid::default_instance());
#endif
}

JingleMessage::JingleMessage(const JingleMessage& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:p2p.JingleMessage)
}

void JingleMessage::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  fromjid_ = NULL;
  tojid_ = NULL;
  content_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

JingleMessage::~JingleMessage() {
  // @@protoc_insertion_point(destructor:p2p.JingleMessage)
  SharedDtor();
}

void JingleMessage::SharedDtor() {
  if (content_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete content_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete fromjid_;
    delete tojid_;
  }
}

void JingleMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const JingleMessage& JingleMessage::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_p2p_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_p2p_2eproto();
#endif
  return *default_instance_;
}

JingleMessage* JingleMessage::default_instance_ = NULL;

JingleMessage* JingleMessage::New() const {
  return new JingleMessage;
}

void JingleMessage::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_fromjid()) {
      if (fromjid_ != NULL) fromjid_->::core::Jid::Clear();
    }
    if (has_tojid()) {
      if (tojid_ != NULL) tojid_->::core::Jid::Clear();
    }
    if (has_content()) {
      if (content_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        content_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool JingleMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:p2p.JingleMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .core.Jid fromJid = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_fromjid()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_toJid;
        break;
      }

      // required .core.Jid toJid = 2;
      case 2: {
        if (tag == 18) {
         parse_toJid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_tojid()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_content;
        break;
      }

      // required string content = 3;
      case 3: {
        if (tag == 26) {
         parse_content:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_content()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:p2p.JingleMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:p2p.JingleMessage)
  return false;
#undef DO_
}

void JingleMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:p2p.JingleMessage)
  // required .core.Jid fromJid = 1;
  if (has_fromjid()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->fromjid(), output);
  }

  // required .core.Jid toJid = 2;
  if (has_tojid()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, this->tojid(), output);
  }

  // required string content = 3;
  if (has_content()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->content(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:p2p.JingleMessage)
}

int JingleMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .core.Jid fromJid = 1;
    if (has_fromjid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->fromjid());
    }

    // required .core.Jid toJid = 2;
    if (has_tojid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->tojid());
    }

    // required string content = 3;
    if (has_content()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->content());
    }

  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void JingleMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const JingleMessage*>(&from));
}

void JingleMessage::MergeFrom(const JingleMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_fromjid()) {
      mutable_fromjid()->::core::Jid::MergeFrom(from.fromjid());
    }
    if (from.has_tojid()) {
      mutable_tojid()->::core::Jid::MergeFrom(from.tojid());
    }
    if (from.has_content()) {
      set_content(from.content());
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void JingleMessage::CopyFrom(const JingleMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JingleMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  if (has_fromjid()) {
    if (!this->fromjid().IsInitialized()) return false;
  }
  if (has_tojid()) {
    if (!this->tojid().IsInitialized()) return false;
  }
  return true;
}

void JingleMessage::Swap(JingleMessage* other) {
  if (other != this) {
    std::swap(fromjid_, other->fromjid_);
    std::swap(tojid_, other->tojid_);
    std::swap(content_, other->content_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.swap(other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string JingleMessage::GetTypeName() const {
  return "p2p.JingleMessage";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace p2p

// @@protoc_insertion_point(global_scope)
