// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Resource Binding
type AuthenticationReq_ResourceType int32

const (
	AuthenticationReq_WINPC   AuthenticationReq_ResourceType = 0
	AuthenticationReq_ANDROID AuthenticationReq_ResourceType = 1
	AuthenticationReq_IPHONE  AuthenticationReq_ResourceType = 2
	AuthenticationReq_IPAD    AuthenticationReq_ResourceType = 3
)

var AuthenticationReq_ResourceType_name = map[int32]string{
	0: "WINPC",
	1: "ANDROID",
	2: "IPHONE",
	3: "IPAD",
}

var AuthenticationReq_ResourceType_value = map[string]int32{
	"WINPC":   0,
	"ANDROID": 1,
	"IPHONE":  2,
	"IPAD":    3,
}

func (x AuthenticationReq_ResourceType) Enum() *AuthenticationReq_ResourceType {
	p := new(AuthenticationReq_ResourceType)
	*p = x
	return p
}

func (x AuthenticationReq_ResourceType) String() string {
	return proto.EnumName(AuthenticationReq_ResourceType_name, int32(x))
}

func (x *AuthenticationReq_ResourceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AuthenticationReq_ResourceType_value, data, "AuthenticationReq_ResourceType")
	if err != nil {
		return err
	}
	*x = AuthenticationReq_ResourceType(value)
	return nil
}

func (AuthenticationReq_ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{1, 0}
}

// http://xmpp.org/rfcs/rfc6120.html
type Jid struct {
	Id                   *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Domain               *string  `protobuf:"bytes,2,opt,name=domain" json:"domain,omitempty"`
	Resource             *string  `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Jid) Reset()         { *m = Jid{} }
func (m *Jid) String() string { return proto.CompactTextString(m) }
func (*Jid) ProtoMessage()    {}
func (*Jid) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

func (m *Jid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jid.Unmarshal(m, b)
}
func (m *Jid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jid.Marshal(b, m, deterministic)
}
func (m *Jid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jid.Merge(m, src)
}
func (m *Jid) XXX_Size() int {
	return xxx_messageInfo_Jid.Size(m)
}
func (m *Jid) XXX_DiscardUnknown() {
	xxx_messageInfo_Jid.DiscardUnknown(m)
}

var xxx_messageInfo_Jid proto.InternalMessageInfo

func (m *Jid) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Jid) GetDomain() string {
	if m != nil && m.Domain != nil {
		return *m.Domain
	}
	return ""
}

func (m *Jid) GetResource() string {
	if m != nil && m.Resource != nil {
		return *m.Resource
	}
	return ""
}

type AuthenticationReq struct {
	// The term "bare JID" refers to an XMPP address of the form <localpart@domainpart> (for an account at a server) or of the form <domainpart> (for a server).
	Jid                  *Jid                            `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	Password             *string                         `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	ResourceType         *AuthenticationReq_ResourceType `protobuf:"varint,3,opt,name=resourceType,enum=core.AuthenticationReq_ResourceType,def=0" json:"resourceType,omitempty"`
	ResourceName         *string                         `protobuf:"bytes,4,opt,name=resourceName" json:"resourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *AuthenticationReq) Reset()         { *m = AuthenticationReq{} }
func (m *AuthenticationReq) String() string { return proto.CompactTextString(m) }
func (*AuthenticationReq) ProtoMessage()    {}
func (*AuthenticationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{1}
}

func (m *AuthenticationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationReq.Unmarshal(m, b)
}
func (m *AuthenticationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationReq.Marshal(b, m, deterministic)
}
func (m *AuthenticationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationReq.Merge(m, src)
}
func (m *AuthenticationReq) XXX_Size() int {
	return xxx_messageInfo_AuthenticationReq.Size(m)
}
func (m *AuthenticationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationReq proto.InternalMessageInfo

const Default_AuthenticationReq_ResourceType AuthenticationReq_ResourceType = AuthenticationReq_WINPC

func (m *AuthenticationReq) GetJid() *Jid {
	if m != nil {
		return m.Jid
	}
	return nil
}

func (m *AuthenticationReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *AuthenticationReq) GetResourceType() AuthenticationReq_ResourceType {
	if m != nil && m.ResourceType != nil {
		return *m.ResourceType
	}
	return Default_AuthenticationReq_ResourceType
}

func (m *AuthenticationReq) GetResourceName() string {
	if m != nil && m.ResourceName != nil {
		return *m.ResourceName
	}
	return ""
}

type Response struct {
	Status               *int32   `protobuf:"varint,1,req,name=status" json:"status,omitempty"`
	Cause                *string  `protobuf:"bytes,2,opt,name=cause" json:"cause,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *Response) GetCause() string {
	if m != nil && m.Cause != nil {
		return *m.Cause
	}
	return ""
}

type AuthenticationResp struct {
	Resp                 *Response `protobuf:"bytes,1,req,name=resp" json:"resp,omitempty"`
	FullJid              *Jid      `protobuf:"bytes,3,opt,name=fullJid" json:"fullJid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AuthenticationResp) Reset()         { *m = AuthenticationResp{} }
func (m *AuthenticationResp) String() string { return proto.CompactTextString(m) }
func (*AuthenticationResp) ProtoMessage()    {}
func (*AuthenticationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{3}
}

func (m *AuthenticationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationResp.Unmarshal(m, b)
}
func (m *AuthenticationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationResp.Marshal(b, m, deterministic)
}
func (m *AuthenticationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationResp.Merge(m, src)
}
func (m *AuthenticationResp) XXX_Size() int {
	return xxx_messageInfo_AuthenticationResp.Size(m)
}
func (m *AuthenticationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationResp proto.InternalMessageInfo

func (m *AuthenticationResp) GetResp() *Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (m *AuthenticationResp) GetFullJid() *Jid {
	if m != nil {
		return m.FullJid
	}
	return nil
}

type Heartbeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{4}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

type HeartbeatAck struct {
	FromJid              *Jid     `protobuf:"bytes,1,req,name=fromJid" json:"fromJid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatAck) Reset()         { *m = HeartbeatAck{} }
func (m *HeartbeatAck) String() string { return proto.CompactTextString(m) }
func (*HeartbeatAck) ProtoMessage()    {}
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{5}
}

func (m *HeartbeatAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatAck.Unmarshal(m, b)
}
func (m *HeartbeatAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatAck.Marshal(b, m, deterministic)
}
func (m *HeartbeatAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatAck.Merge(m, src)
}
func (m *HeartbeatAck) XXX_Size() int {
	return xxx_messageInfo_HeartbeatAck.Size(m)
}
func (m *HeartbeatAck) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatAck.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatAck proto.InternalMessageInfo

func (m *HeartbeatAck) GetFromJid() *Jid {
	if m != nil {
		return m.FromJid
	}
	return nil
}

func init() {
	proto.RegisterEnum("core.AuthenticationReq_ResourceType", AuthenticationReq_ResourceType_name, AuthenticationReq_ResourceType_value)
	proto.RegisterType((*Jid)(nil), "core.Jid")
	proto.RegisterType((*AuthenticationReq)(nil), "core.AuthenticationReq")
	proto.RegisterType((*Response)(nil), "core.Response")
	proto.RegisterType((*AuthenticationResp)(nil), "core.AuthenticationResp")
	proto.RegisterType((*Heartbeat)(nil), "core.Heartbeat")
	proto.RegisterType((*HeartbeatAck)(nil), "core.HeartbeatAck")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_f7e43720d1edc0fe) }

var fileDescriptor_f7e43720d1edc0fe = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xbb, 0x4f, 0xe3, 0x40,
	0x18, 0xc4, 0xcf, 0x8f, 0x3c, 0xfc, 0x25, 0x8a, 0x7c, 0x9f, 0x4e, 0x27, 0xeb, 0xae, 0x89, 0xf6,
	0xae, 0x48, 0x95, 0x22, 0x34, 0x08, 0xd1, 0x18, 0x82, 0x14, 0xbb, 0x70, 0xa2, 0x15, 0x12, 0x15,
	0xc5, 0x62, 0x2f, 0x62, 0x21, 0xf1, 0x9a, 0xdd, 0xb5, 0x10, 0x7f, 0x3d, 0xc8, 0xaf, 0x90, 0x00,
	0x9d, 0xe7, 0x1b, 0xeb, 0x37, 0x9e, 0x31, 0x40, 0x2a, 0x15, 0x9f, 0x17, 0x4a, 0x1a, 0x89, 0x6e,
	0xf5, 0x4c, 0x22, 0x70, 0x62, 0x91, 0xe1, 0x04, 0x6c, 0x91, 0x05, 0xd6, 0xd4, 0x9e, 0x79, 0xd4,
	0x16, 0x19, 0xfe, 0x86, 0x7e, 0x26, 0x77, 0x4c, 0xe4, 0x81, 0x3d, 0xb5, 0x66, 0x1e, 0x6d, 0x15,
	0xfe, 0x81, 0xa1, 0xe2, 0x5a, 0x96, 0x2a, 0xe5, 0x81, 0x53, 0x3b, 0x7b, 0x4d, 0xde, 0x2c, 0xf8,
	0x19, 0x96, 0xe6, 0x81, 0xe7, 0x46, 0xa4, 0xcc, 0x08, 0x99, 0x53, 0xfe, 0x8c, 0x7f, 0xc1, 0x79,
	0x6c, 0xd1, 0xa3, 0x85, 0x37, 0xaf, 0x3f, 0x20, 0x16, 0x19, 0xad, 0xae, 0x15, 0xae, 0x60, 0x5a,
	0xbf, 0x48, 0x95, 0xb5, 0x41, 0x7b, 0x8d, 0x6b, 0x18, 0x77, 0xe8, 0xeb, 0xd7, 0xa2, 0x89, 0x9b,
	0x2c, 0xfe, 0x37, 0x84, 0x2f, 0x39, 0x73, 0x7a, 0xf0, 0xee, 0x59, 0xef, 0x26, 0x4a, 0x36, 0x97,
	0xf4, 0x08, 0x80, 0xe4, 0x03, 0x98, 0xb0, 0x1d, 0x0f, 0xdc, 0x3a, 0xf0, 0xe8, 0x46, 0xce, 0x61,
	0x7c, 0x08, 0x42, 0x0f, 0x1a, 0x94, 0xff, 0x03, 0x47, 0x30, 0x08, 0x93, 0x25, 0x5d, 0x47, 0x4b,
	0xdf, 0x42, 0x80, 0x7e, 0xb4, 0x59, 0xad, 0x93, 0x2b, 0xdf, 0xc6, 0x21, 0xb8, 0xd1, 0x26, 0x5c,
	0xfa, 0x0e, 0x39, 0x85, 0x21, 0xe5, 0xba, 0x90, 0xb9, 0xe6, 0xd5, 0x82, 0xda, 0x30, 0x53, 0xea,
	0xba, 0x7a, 0x8f, 0xb6, 0x0a, 0x7f, 0x41, 0x2f, 0x65, 0xa5, 0xe6, 0x6d, 0xdf, 0x46, 0x90, 0x5b,
	0xc0, 0xcf, 0x95, 0x74, 0x81, 0x04, 0x5c, 0xc5, 0x75, 0xd1, 0x8e, 0x37, 0x69, 0xaa, 0x77, 0x09,
	0xb4, 0xf6, 0xf0, 0x1f, 0x0c, 0xee, 0xcb, 0xed, 0x36, 0x16, 0x59, 0xbd, 0xd0, 0xd1, 0xc6, 0x9d,
	0x43, 0x46, 0xe0, 0xad, 0x38, 0x53, 0xe6, 0x8e, 0x33, 0x43, 0x4e, 0x60, 0xbc, 0x17, 0x61, 0xfa,
	0x54, 0x13, 0x94, 0xdc, 0xc5, 0xdf, 0xfd, 0xa5, 0xce, 0xb9, 0xb0, 0x57, 0xce, 0x7b, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x33, 0x8e, 0x67, 0xc2, 0x3e, 0x02, 0x00, 0x00,
}
