// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im.proto

package im

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	core "lightyear/proto/core"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnumMessageElement int32

const (
	EnumMessageElement_TEXT   EnumMessageElement = 0
	EnumMessageElement_SMILEY EnumMessageElement = 1
	EnumMessageElement_BITMAP EnumMessageElement = 2
)

var EnumMessageElement_name = map[int32]string{
	0: "TEXT",
	1: "SMILEY",
	2: "BITMAP",
}

var EnumMessageElement_value = map[string]int32{
	"TEXT":   0,
	"SMILEY": 1,
	"BITMAP": 2,
}

func (x EnumMessageElement) Enum() *EnumMessageElement {
	p := new(EnumMessageElement)
	*p = x
	return p
}

func (x EnumMessageElement) String() string {
	return proto.EnumName(EnumMessageElement_name, int32(x))
}

func (x *EnumMessageElement) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EnumMessageElement_value, data, "EnumMessageElement")
	if err != nil {
		return err
	}
	*x = EnumMessageElement(value)
	return nil
}

func (EnumMessageElement) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{0}
}

type Presence_Show int32

const (
	Presence_ONLINE  Presence_Show = 0
	Presence_OFFLINE Presence_Show = 1
	Presence_AWAY    Presence_Show = 2
)

var Presence_Show_name = map[int32]string{
	0: "ONLINE",
	1: "OFFLINE",
	2: "AWAY",
}

var Presence_Show_value = map[string]int32{
	"ONLINE":  0,
	"OFFLINE": 1,
	"AWAY":    2,
}

func (x Presence_Show) Enum() *Presence_Show {
	p := new(Presence_Show)
	*p = x
	return p
}

func (x Presence_Show) String() string {
	return proto.EnumName(Presence_Show_name, int32(x))
}

func (x *Presence_Show) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Presence_Show_value, data, "Presence_Show")
	if err != nil {
		return err
	}
	*x = Presence_Show(value)
	return nil
}

func (Presence_Show) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{0, 0}
}

// presence
type Presence struct {
	FromJid *core.Jid `protobuf:"bytes,1,opt,name=fromJid" json:"fromJid,omitempty"`
	ToJid   *core.Jid `protobuf:"bytes,2,opt,name=toJid" json:"toJid,omitempty"`
	// optional string type = 3;
	Priority             *int32         `protobuf:"varint,4,opt,name=priority" json:"priority,omitempty"`
	Show                 *Presence_Show `protobuf:"varint,5,opt,name=show,enum=im.Presence_Show" json:"show,omitempty"`
	Status               *string        `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Presence) Reset()         { *m = Presence{} }
func (m *Presence) String() string { return proto.CompactTextString(m) }
func (*Presence) ProtoMessage()    {}
func (*Presence) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{0}
}

func (m *Presence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Presence.Unmarshal(m, b)
}
func (m *Presence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Presence.Marshal(b, m, deterministic)
}
func (m *Presence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Presence.Merge(m, src)
}
func (m *Presence) XXX_Size() int {
	return xxx_messageInfo_Presence.Size(m)
}
func (m *Presence) XXX_DiscardUnknown() {
	xxx_messageInfo_Presence.DiscardUnknown(m)
}

var xxx_messageInfo_Presence proto.InternalMessageInfo

func (m *Presence) GetFromJid() *core.Jid {
	if m != nil {
		return m.FromJid
	}
	return nil
}

func (m *Presence) GetToJid() *core.Jid {
	if m != nil {
		return m.ToJid
	}
	return nil
}

func (m *Presence) GetPriority() int32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

func (m *Presence) GetShow() Presence_Show {
	if m != nil && m.Show != nil {
		return *m.Show
	}
	return Presence_ONLINE
}

func (m *Presence) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

// roster get
type RosterReq struct {
	Jid                  *core.Jid `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RosterReq) Reset()         { *m = RosterReq{} }
func (m *RosterReq) String() string { return proto.CompactTextString(m) }
func (*RosterReq) ProtoMessage()    {}
func (*RosterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{1}
}

func (m *RosterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RosterReq.Unmarshal(m, b)
}
func (m *RosterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RosterReq.Marshal(b, m, deterministic)
}
func (m *RosterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RosterReq.Merge(m, src)
}
func (m *RosterReq) XXX_Size() int {
	return xxx_messageInfo_RosterReq.Size(m)
}
func (m *RosterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RosterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RosterReq proto.InternalMessageInfo

func (m *RosterReq) GetJid() *core.Jid {
	if m != nil {
		return m.Jid
	}
	return nil
}

type RosterItem struct {
	Jid          *core.Jid `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	OnlineStatus *int32    `protobuf:"varint,2,req,name=onlineStatus" json:"onlineStatus,omitempty"`
	Name         *string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Nickname     *string   `protobuf:"bytes,4,opt,name=nickname" json:"nickname,omitempty"`
	Description  *string   `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Position     *string   `protobuf:"bytes,6,opt,name=position" json:"position,omitempty"`
	Department   *string   `protobuf:"bytes,7,opt,name=department" json:"department,omitempty"`
	// optional string subscription = 6;
	GroupTag             []string `protobuf:"bytes,8,rep,name=groupTag" json:"groupTag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RosterItem) Reset()         { *m = RosterItem{} }
func (m *RosterItem) String() string { return proto.CompactTextString(m) }
func (*RosterItem) ProtoMessage()    {}
func (*RosterItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{2}
}

func (m *RosterItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RosterItem.Unmarshal(m, b)
}
func (m *RosterItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RosterItem.Marshal(b, m, deterministic)
}
func (m *RosterItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RosterItem.Merge(m, src)
}
func (m *RosterItem) XXX_Size() int {
	return xxx_messageInfo_RosterItem.Size(m)
}
func (m *RosterItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RosterItem.DiscardUnknown(m)
}

var xxx_messageInfo_RosterItem proto.InternalMessageInfo

func (m *RosterItem) GetJid() *core.Jid {
	if m != nil {
		return m.Jid
	}
	return nil
}

func (m *RosterItem) GetOnlineStatus() int32 {
	if m != nil && m.OnlineStatus != nil {
		return *m.OnlineStatus
	}
	return 0
}

func (m *RosterItem) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RosterItem) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *RosterItem) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *RosterItem) GetPosition() string {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return ""
}

func (m *RosterItem) GetDepartment() string {
	if m != nil && m.Department != nil {
		return *m.Department
	}
	return ""
}

func (m *RosterItem) GetGroupTag() []string {
	if m != nil {
		return m.GroupTag
	}
	return nil
}

type RosterResp struct {
	RosterItems          []*RosterItem `protobuf:"bytes,1,rep,name=rosterItems" json:"rosterItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RosterResp) Reset()         { *m = RosterResp{} }
func (m *RosterResp) String() string { return proto.CompactTextString(m) }
func (*RosterResp) ProtoMessage()    {}
func (*RosterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{3}
}

func (m *RosterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RosterResp.Unmarshal(m, b)
}
func (m *RosterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RosterResp.Marshal(b, m, deterministic)
}
func (m *RosterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RosterResp.Merge(m, src)
}
func (m *RosterResp) XXX_Size() int {
	return xxx_messageInfo_RosterResp.Size(m)
}
func (m *RosterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RosterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RosterResp proto.InternalMessageInfo

func (m *RosterResp) GetRosterItems() []*RosterItem {
	if m != nil {
		return m.RosterItems
	}
	return nil
}

type PresenceReq struct {
	Jid                  *core.Jid `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PresenceReq) Reset()         { *m = PresenceReq{} }
func (m *PresenceReq) String() string { return proto.CompactTextString(m) }
func (*PresenceReq) ProtoMessage()    {}
func (*PresenceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{4}
}

func (m *PresenceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PresenceReq.Unmarshal(m, b)
}
func (m *PresenceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PresenceReq.Marshal(b, m, deterministic)
}
func (m *PresenceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PresenceReq.Merge(m, src)
}
func (m *PresenceReq) XXX_Size() int {
	return xxx_messageInfo_PresenceReq.Size(m)
}
func (m *PresenceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PresenceReq.DiscardUnknown(m)
}

var xxx_messageInfo_PresenceReq proto.InternalMessageInfo

func (m *PresenceReq) GetJid() *core.Jid {
	if m != nil {
		return m.Jid
	}
	return nil
}

type PresenceResp struct {
	Jids                 []*core.Jid `protobuf:"bytes,1,rep,name=jids" json:"jids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PresenceResp) Reset()         { *m = PresenceResp{} }
func (m *PresenceResp) String() string { return proto.CompactTextString(m) }
func (*PresenceResp) ProtoMessage()    {}
func (*PresenceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{5}
}

func (m *PresenceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PresenceResp.Unmarshal(m, b)
}
func (m *PresenceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PresenceResp.Marshal(b, m, deterministic)
}
func (m *PresenceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PresenceResp.Merge(m, src)
}
func (m *PresenceResp) XXX_Size() int {
	return xxx_messageInfo_PresenceResp.Size(m)
}
func (m *PresenceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PresenceResp.DiscardUnknown(m)
}

var xxx_messageInfo_PresenceResp proto.InternalMessageInfo

func (m *PresenceResp) GetJids() []*core.Jid {
	if m != nil {
		return m.Jids
	}
	return nil
}

type MessageElement struct {
	Kind                 *EnumMessageElement `protobuf:"varint,1,req,name=kind,enum=im.EnumMessageElement" json:"kind,omitempty"`
	Data                 []byte              `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MessageElement) Reset()         { *m = MessageElement{} }
func (m *MessageElement) String() string { return proto.CompactTextString(m) }
func (*MessageElement) ProtoMessage()    {}
func (*MessageElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{6}
}

func (m *MessageElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageElement.Unmarshal(m, b)
}
func (m *MessageElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageElement.Marshal(b, m, deterministic)
}
func (m *MessageElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageElement.Merge(m, src)
}
func (m *MessageElement) XXX_Size() int {
	return xxx_messageInfo_MessageElement.Size(m)
}
func (m *MessageElement) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageElement.DiscardUnknown(m)
}

var xxx_messageInfo_MessageElement proto.InternalMessageInfo

func (m *MessageElement) GetKind() EnumMessageElement {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return EnumMessageElement_TEXT
}

func (m *MessageElement) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// chat message
// 5.2.2 type attribute
// 1. chat
// 2. group chat
// 3. headline
type ChatMessage struct {
	FromJid              *core.Jid         `protobuf:"bytes,1,req,name=fromJid" json:"fromJid,omitempty"`
	ToJid                *core.Jid         `protobuf:"bytes,2,req,name=toJid" json:"toJid,omitempty"`
	Body                 []*MessageElement `protobuf:"bytes,3,rep,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{7}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetFromJid() *core.Jid {
	if m != nil {
		return m.FromJid
	}
	return nil
}

func (m *ChatMessage) GetToJid() *core.Jid {
	if m != nil {
		return m.ToJid
	}
	return nil
}

func (m *ChatMessage) GetBody() []*MessageElement {
	if m != nil {
		return m.Body
	}
	return nil
}

// server message push
type AlertMessage struct {
	Body                 *string  `protobuf:"bytes,3,req,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlertMessage) Reset()         { *m = AlertMessage{} }
func (m *AlertMessage) String() string { return proto.CompactTextString(m) }
func (*AlertMessage) ProtoMessage()    {}
func (*AlertMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{8}
}

func (m *AlertMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertMessage.Unmarshal(m, b)
}
func (m *AlertMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertMessage.Marshal(b, m, deterministic)
}
func (m *AlertMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertMessage.Merge(m, src)
}
func (m *AlertMessage) XXX_Size() int {
	return xxx_messageInfo_AlertMessage.Size(m)
}
func (m *AlertMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AlertMessage proto.InternalMessageInfo

func (m *AlertMessage) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func init() {
	proto.RegisterEnum("im.EnumMessageElement", EnumMessageElement_name, EnumMessageElement_value)
	proto.RegisterEnum("im.Presence_Show", Presence_Show_name, Presence_Show_value)
	proto.RegisterType((*Presence)(nil), "im.Presence")
	proto.RegisterType((*RosterReq)(nil), "im.RosterReq")
	proto.RegisterType((*RosterItem)(nil), "im.RosterItem")
	proto.RegisterType((*RosterResp)(nil), "im.RosterResp")
	proto.RegisterType((*PresenceReq)(nil), "im.PresenceReq")
	proto.RegisterType((*PresenceResp)(nil), "im.PresenceResp")
	proto.RegisterType((*MessageElement)(nil), "im.MessageElement")
	proto.RegisterType((*ChatMessage)(nil), "im.ChatMessage")
	proto.RegisterType((*AlertMessage)(nil), "im.AlertMessage")
}

func init() { proto.RegisterFile("im.proto", fileDescriptor_36f2114a3e4ddb9e) }

var fileDescriptor_36f2114a3e4ddb9e = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x3f, 0xd2, 0x24, 0xe3, 0x28, 0x0a, 0x73, 0x88, 0xac, 0x22, 0xc0, 0x32, 0x02, 0x99,
	0x48, 0xa4, 0x28, 0x07, 0x8e, 0x48, 0x29, 0x4a, 0x45, 0xaa, 0xa6, 0x8d, 0x36, 0x91, 0xa0, 0xdc,
	0x4c, 0xbc, 0x24, 0xdb, 0xc6, 0x5e, 0xb3, 0xbb, 0x51, 0x15, 0xf1, 0x3f, 0xf9, 0x2b, 0x5c, 0xd1,
	0xae, 0x6b, 0x37, 0x29, 0x88, 0xde, 0xe6, 0xbd, 0x79, 0xeb, 0x99, 0x79, 0x33, 0x86, 0x06, 0x4b,
	0xfb, 0xb9, 0xe0, 0x8a, 0xa3, 0xcd, 0xd2, 0x23, 0x58, 0x70, 0x41, 0x0b, 0x1c, 0xfe, 0xb2, 0xa0,
	0x31, 0x15, 0x54, 0xd2, 0x6c, 0x41, 0xf1, 0x25, 0xd4, 0xbf, 0x0b, 0x9e, 0x9e, 0xb1, 0xc4, 0xb7,
	0x02, 0x2b, 0xf2, 0x06, 0xcd, 0xbe, 0x91, 0x9e, 0xb1, 0x84, 0x94, 0x19, 0x7c, 0x01, 0x35, 0xc5,
	0xb5, 0xc4, 0x7e, 0x28, 0x29, 0x78, 0x3c, 0x82, 0x46, 0x2e, 0x18, 0x17, 0x4c, 0x6d, 0x7d, 0x37,
	0xb0, 0xa2, 0x1a, 0xa9, 0x30, 0xbe, 0x02, 0x57, 0xae, 0xf8, 0xad, 0x5f, 0x0b, 0xac, 0xa8, 0x3d,
	0x78, 0xd2, 0x67, 0x69, 0xbf, 0xac, 0xde, 0x9f, 0xad, 0xf8, 0x2d, 0x31, 0x69, 0xec, 0xc2, 0xa1,
	0x54, 0xb1, 0xda, 0x48, 0xff, 0x30, 0xb0, 0xa2, 0x26, 0xb9, 0x43, 0xe1, 0x1b, 0x70, 0xb5, 0x0a,
	0x01, 0x0e, 0x2f, 0x2f, 0xce, 0xc7, 0x17, 0xa3, 0xce, 0x01, 0x7a, 0x50, 0xbf, 0x3c, 0x3d, 0x35,
	0xc0, 0xc2, 0x06, 0xb8, 0xc3, 0xcf, 0xc3, 0xab, 0x8e, 0x1d, 0x46, 0xd0, 0x24, 0x5c, 0x2a, 0x2a,
	0x08, 0xfd, 0x81, 0x4f, 0xc1, 0xb9, 0x36, 0x43, 0xd9, 0xfb, 0x1d, 0x6b, 0x36, 0xfc, 0x6d, 0x01,
	0x14, 0xd2, 0xb1, 0xa2, 0xe9, 0x7f, 0xb5, 0x18, 0x42, 0x8b, 0x67, 0x6b, 0x96, 0xd1, 0x59, 0xd1,
	0x9e, 0x1d, 0xd8, 0x51, 0x8d, 0xec, 0x71, 0x88, 0xe0, 0x66, 0x71, 0x4a, 0x7d, 0xc7, 0xb4, 0x6e,
	0x62, 0xed, 0x49, 0xc6, 0x16, 0x37, 0x86, 0x77, 0x0d, 0x5f, 0x61, 0x0c, 0xc0, 0x4b, 0xa8, 0x5c,
	0x08, 0x96, 0x2b, 0xc6, 0x33, 0x63, 0x4d, 0x93, 0xec, 0x52, 0xc6, 0x51, 0x2e, 0x99, 0x49, 0x17,
	0x86, 0x54, 0x18, 0x9f, 0x03, 0x24, 0x34, 0x8f, 0x85, 0x4a, 0x69, 0xa6, 0xfc, 0xba, 0xc9, 0xee,
	0x30, 0xfa, 0xed, 0x52, 0xf0, 0x4d, 0x3e, 0x8f, 0x97, 0x7e, 0x23, 0x70, 0xf4, 0xdb, 0x12, 0x87,
	0x1f, 0xca, 0xc1, 0x09, 0x95, 0x39, 0xbe, 0x03, 0x4f, 0x54, 0x36, 0x48, 0xdf, 0x0a, 0x9c, 0xc8,
	0x1b, 0xb4, 0xf5, 0x8a, 0xee, 0xdd, 0x21, 0xbb, 0x92, 0xb0, 0x07, 0x5e, 0xb9, 0xbd, 0x47, 0x5d,
	0x7e, 0x0b, 0xad, 0x7b, 0xad, 0xcc, 0xf1, 0x19, 0xb8, 0xd7, 0x2c, 0x29, 0xcb, 0xec, 0xa8, 0x0d,
	0x1d, 0x4e, 0xa1, 0x3d, 0xa1, 0x52, 0xc6, 0x4b, 0x3a, 0x5a, 0x53, 0x33, 0x48, 0x0f, 0xdc, 0x1b,
	0x96, 0x15, 0x9f, 0x6f, 0x0f, 0xba, 0xba, 0xaf, 0x51, 0xb6, 0x49, 0xf7, 0x55, 0xc4, 0x68, 0xf4,
	0x0a, 0x92, 0x58, 0xc5, 0x66, 0x3d, 0x2d, 0x62, 0xe2, 0xf0, 0x27, 0x78, 0x1f, 0x57, 0xb1, 0xba,
	0xd3, 0xef, 0xdf, 0xba, 0xfd, 0xf8, 0xad, 0xdb, 0xff, 0xbc, 0xf5, 0xd7, 0xe0, 0x7e, 0xe3, 0xc9,
	0xd6, 0x77, 0xcc, 0x14, 0xa8, 0x9b, 0x7a, 0xd8, 0x90, 0xce, 0x87, 0x21, 0xb4, 0x86, 0x6b, 0x2a,
	0xaa, 0xea, 0x58, 0xbd, 0xb3, 0xf5, 0x8d, 0xe8, 0xb8, 0xf7, 0x1e, 0xf0, 0xef, 0x81, 0xf4, 0x45,
	0xcf, 0x47, 0x5f, 0xe6, 0x9d, 0x03, 0x7d, 0xf4, 0xb3, 0xc9, 0xf8, 0x7c, 0x74, 0xd5, 0xb1, 0x74,
	0x7c, 0x32, 0x9e, 0x4f, 0x86, 0xd3, 0x8e, 0x7d, 0xd2, 0xfd, 0xe4, 0x7c, 0xc5, 0x35, 0x5b, 0xae,
	0xd4, 0x96, 0xc6, 0xe2, 0xd8, 0xfc, 0xd7, 0xc7, 0x2c, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0xa8,
	0xf3, 0xbf, 0xb6, 0xf5, 0x03, 0x00, 0x00,
}
