// Code generated by protoc-gen-go.
// source: p2p.proto
// DO NOT EDIT!

package p2p

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"
import core "lightyear/proto/core"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type JingleMessage struct {
	FromJid          *core.Jid `protobuf:"bytes,1,req,name=fromJid" json:"fromJid,omitempty"`
	ToJid            *core.Jid `protobuf:"bytes,2,req,name=toJid" json:"toJid,omitempty"`
	Content          *string   `protobuf:"bytes,3,req,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *JingleMessage) Reset()         { *m = JingleMessage{} }
func (m *JingleMessage) String() string { return proto.CompactTextString(m) }
func (*JingleMessage) ProtoMessage()    {}

func (m *JingleMessage) GetFromJid() *core.Jid {
	if m != nil {
		return m.FromJid
	}
	return nil
}

func (m *JingleMessage) GetToJid() *core.Jid {
	if m != nil {
		return m.ToJid
	}
	return nil
}

func (m *JingleMessage) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func init() {
}
