// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p2p.proto

package p2p

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JingleMessage struct {
	FromJid              *Jid     `protobuf:"bytes,1,req,name=fromJid" json:"fromJid,omitempty"`
	ToJid                *Jid     `protobuf:"bytes,2,req,name=toJid" json:"toJid,omitempty"`
	Content              *string  `protobuf:"bytes,3,req,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JingleMessage) Reset()         { *m = JingleMessage{} }
func (m *JingleMessage) String() string { return proto.CompactTextString(m) }
func (*JingleMessage) ProtoMessage()    {}
func (*JingleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{0}
}

func (m *JingleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JingleMessage.Unmarshal(m, b)
}
func (m *JingleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JingleMessage.Marshal(b, m, deterministic)
}
func (m *JingleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JingleMessage.Merge(m, src)
}
func (m *JingleMessage) XXX_Size() int {
	return xxx_messageInfo_JingleMessage.Size(m)
}
func (m *JingleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_JingleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_JingleMessage proto.InternalMessageInfo

func (m *JingleMessage) GetFromJid() *Jid {
	if m != nil {
		return m.FromJid
	}
	return nil
}

func (m *JingleMessage) GetToJid() *Jid {
	if m != nil {
		return m.ToJid
	}
	return nil
}

func (m *JingleMessage) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*JingleMessage)(nil), "p2p.JingleMessage")
}

func init() { proto.RegisterFile("p2p.proto", fileDescriptor_e7fdddb109e6467a) }

var fileDescriptor_e7fdddb109e6467a = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x30, 0x2a, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x30, 0x2a, 0x90, 0xe2, 0x4a, 0xce, 0x2f, 0x4a,
	0x85, 0x08, 0x28, 0xe5, 0x73, 0xf1, 0x7a, 0x65, 0xe6, 0xa5, 0xe7, 0xa4, 0xfa, 0xa6, 0x16, 0x17,
	0x27, 0xa6, 0xa7, 0x0a, 0x29, 0x73, 0xb1, 0xa7, 0x15, 0xe5, 0xe7, 0x7a, 0x65, 0xa6, 0x48, 0x30,
	0x2a, 0x30, 0x69, 0x70, 0x1b, 0x71, 0xea, 0x81, 0x95, 0x7b, 0x65, 0xa6, 0x04, 0xc1, 0x64, 0x84,
	0xe4, 0xb9, 0x58, 0x4b, 0xf2, 0x41, 0x4a, 0x98, 0xd0, 0x95, 0x40, 0xc4, 0x85, 0x24, 0xb8, 0xd8,
	0x93, 0xf3, 0xf3, 0x4a, 0x52, 0xf3, 0x4a, 0x24, 0x98, 0x15, 0x98, 0x34, 0x38, 0x83, 0x60, 0x5c,
	0x27, 0x26, 0x0f, 0x66, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x27, 0x55, 0x65, 0xb8, 0x91, 0x00,
	0x00, 0x00,
}
