// Code generated by protoc-gen-go.
// source: localdb.proto
// DO NOT EDIT!

package localdb

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"
import im "im.pb"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type UserProfile struct {
	Id               *string           `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Pw               *string           `protobuf:"bytes,2,opt,name=pw" json:"pw,omitempty"`
	AutoSignin       *bool             `protobuf:"varint,3,opt,name=autoSignin" json:"autoSignin,omitempty"`
	Theme            *int32            `protobuf:"varint,4,opt,name=theme" json:"theme,omitempty"`
	RecentContacts   []string          `protobuf:"bytes,5,rep,name=recentContacts" json:"recentContacts,omitempty"`
	ChatMessages     []*im.ChatMessage `protobuf:"bytes,6,rep,name=chatMessages" json:"chatMessages,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}

func (m *UserProfile) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *UserProfile) GetPw() string {
	if m != nil && m.Pw != nil {
		return *m.Pw
	}
	return ""
}

func (m *UserProfile) GetAutoSignin() bool {
	if m != nil && m.AutoSignin != nil {
		return *m.AutoSignin
	}
	return false
}

func (m *UserProfile) GetTheme() int32 {
	if m != nil && m.Theme != nil {
		return *m.Theme
	}
	return 0
}

func (m *UserProfile) GetRecentContacts() []string {
	if m != nil {
		return m.RecentContacts
	}
	return nil
}

func (m *UserProfile) GetChatMessages() []*im.ChatMessage {
	if m != nil {
		return m.ChatMessages
	}
	return nil
}

type Config struct {
	Profiles         []*UserProfile `protobuf:"bytes,1,rep,name=profiles" json:"profiles,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}

func (m *Config) GetProfiles() []*UserProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func init() {
}
